### ISSUE TITLE
Remove the game rooms to 2

### ISSUE THREAD

**Issue by spbonez** [Aftermath-Gaming/feedback-requests#1]
We don't got much gaming going on.
The voice rooms are a bit too much.

**Comment by LukasRH** [comment]
👎

**Comment by sagooper** [comment]
@LukasRH instead of just downvoting the idea please explain why you would down vote it.

**Comment by LukasRH** [comment]
i dont know

**Comment by sagooper** [comment]
We have removed:
Room with limits 4 - 12
We have added:
Room 3
