### ISSUE TITLE
Less coding channels

### ISSUE THREAD

**Issue by LukasRH** [Aftermath-Gaming/feedback-requests#3]
Remove some of the inactive channels under coding, Only channels really being used is Tech talk, and coding_dev_tech-talk is kinda just the same as tech-talk. And then make the channels for specific languages when they are needed. 

3 of them don't have a single message,
Some of them the last messages are from start November / October.

**Comment by sagooper** [comment]
We are looking into removing inactive channels. and the coding channels are on our list as well
